const ACTION_TYPES = {
  AUTH: {
    LOGOUT: 'LOGOUT',
    LOGIN: 'LOGIN',
    GUEST: 'GUEST',
    USER: {UPDATE_USER: 'UPDATE_USER'},
  },
  CART: {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    RESET_CART: 'RESET_CART',
  },
};

export default ACTION_TYPES;
